name: Java CI with Maven

on:
  push:
    branches: [ "main" ]


jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
   
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

    - name: Upload Maven artifact
      uses: actions/upload-artifact@v4
      with:
          name: web_application
          path: target/*.war

    - name: Login to Azure
      uses: azure/login@v1
      with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
            auth-type: 'SERVICE_PRINCIPAL'

    - name: Get the latest WAR file
      id: latest_war
      run: |
          # Find the most recent JAR file in the target directory
          LATEST_WAR=$(ls -t target/*.war | head -n 1)
          echo "LATEST_WAR=$LATEST_WAR" >> $GITHUB_ENV

    - name: Upload the .war file to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
          app-name: javaapplicationwebapp
          package: ${{ env.LATEST_WAR }}
